### ISSUE TITLE
Response engineering

### ISSUE THREAD

**Issue by appatalks** [appatalks/chatgpt-html#8]
At the moment, Prompts are engineered with the initial prompt to always be sent, along with the last response returned and the next passed input. Works pretty well with simple follow ups:
--  Who was was Zeus? 
--  Did he have kids? 
--  Did he have wives?
and can get maybe 5 or so questions in before the AI seems to get lost.

Pondering: Should I attempt to send the entire conversation from the start?
Possible issue: Token length will get exponentially smaller for new inputs/responses since token takes into both input and output.

**Comment by appatalks** [comment]
One thought is to take masterOutput from localStorage and do something with it in a way that pulls key phrase or words to include it in the input prompt. That way we can compress the stream to only what is needed.

maybe what ever the javascript equivalent to grep -v noise_words. Basically anything not a noun, is what I'm thinking..

**Comment by servingbaby** [comment]
I'll try this solution from ChatGPT response with same issue:

I want a function that removes all non-nouns from text.
ou can use the Natural Language Toolkit (NLTK) library in Python to remove all non-nouns from text. NLTK provides a module called pos_tag that can be used to perform part-of-speech tagging on a given text, which can be used to identify nouns in the text.

Here's an example of a function that takes a string of text as input and returns a string with all non-nouns removed:

import nltk
from nltk.tokenize import word_tokenize

def remove_non_nouns(text):
    # Tokenize the text
    words = word_tokenize(text)
    # Perform part-of-speech tagging on the tokenized words
    tagged_words = nltk.pos_tag(words)
    # Filter out words that are not nouns
    nouns = [word for word, tag in tagged_words if tag.startswith("NN")]
    # Join the filtered words and return the result
    return " ".join(nouns)

You can use this function like this:

text = "The quick brown fox jumps over the lazy dog."
print(remove_non_nouns(text)) 
# Output: "fox dog"

In this example, the pos_tag function is used to perform part-of-speech tagging on the tokenized words. The startswith() method is used to check if the tag of a word starts with "NN", which indicates that the word is a noun. If the word is a noun, it is included in the output, otherwise it is filtered out.

It's worth noting that the NLTK library is not perfect in identifying nouns in text, so it may not always give accurate results. Also this function doesn't handle proper nouns, you can add additional check for that.

**Comment by servingbaby** [comment]
I'm thinking I'll keep last response in addition to the above non-noun output. 

Still though, token limit will become an issue, just a bit later down the line...

**Comment by servingbaby** [comment]
import nltk
from nltk.tokenize import word_tokenize

def keep_verbs_remove_non_nouns(text):
    # Tokenize the text
    tokens = nltk.word_tokenize(text)
    # Tag the tokens with their parts of speech
    pos_tags = nltk.pos_tag(tokens)
    # Keep only the verbs and nouns
    filtered_tokens = [token for token, pos in pos_tags if pos[:2] == 'NN' or pos[:2] == 'VB']
    # Join the filtered tokens back into a single string
    filtered_text = ' '.join(filtered_tokens)
    return filtered_text

**Comment by appatalks** [comment]
Ill probably wait for additional api release as this matures to figure this out with best path forward.
